stages:
  data_prep:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
    params:
      - params.yaml:
          - data
          - features
    outs:
      - data/processed/train.parquet
      - data/processed/test.parquet
      - data/processed/feature_names.json

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.parquet
      - data/processed/feature_names.json
    params:
      - params.yaml:
          - models
          - data
    outs:
      - models/preprocessor.joblib

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/test.parquet
      - data/processed/feature_names.json
      - models/preprocessor.joblib
    outs:
      - reports/metrics.json
      - reports/confusion_matrix.png
